name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest

    outputs:
      next-version: ${{ steps.increment-version.outputs.next-version }}
    
    steps:
      - name: Current version
        id: current-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: Increment version
        id: increment-version
        run: |
          CURRENT="${{ steps.current-version.outputs.version }}"
          NEXT-VERSION="v$(( ${CURRENT:1} + 1 ))"
          echo "next-version=$NEXT-VERSION" >> $GITHUB_OUTPUT
          echo "$NEXT-VERSION" > version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v6
        with:
          name: version
          path: version.txt

  build:
    runs-on: ubuntu-latest
    needs: get-version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Run make
      run: make

    - name: Rename artifact
      run: mv bin/shell bin/shell_v${{ needs.get-version.outputs.next-version }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: shell_v${{ needs.get-version.outputs.next-version }}
        path: bin/shell_v${{ needs.get-version.outputs.next-version }}

  build-release:
    runs-on: ubuntu-latest
    needs: get-version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Run make release=1
      run: make release=1
    
    - name: Rename artifact
      run: mv bin/shell bin/shell_v${{ needs.get-version.outputs.next-version }}-release

    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: shell_v${{ needs.get-version.outputs.next-version }}-release
        path: bin/shell_v${{ needs.get-version.outputs.next-version }}-release